# Run all tests for commits to master

name: jq / main

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install software
        run: |
          sudo apt update && sudo apt -y install bats &&
          sudo curl -L -o /usr/bin/jq  https://github.com/jqlang/jq/releases/download/jq-1.8.0/jq-linux-amd64 &&
          sudo chmod -v 755 /usr/bin/jq

      - name: Run tests for all exercises
        run: bash bin/validate_exercises
